export const mockSalonData = [
  {
    id: 'salon-1',
    name: 'Krupa Beauty Clinic',
    category: 'Beauty Clinic',
    instagramFollowers: '10k',
    location: 'Vadodara, Gujarat',
    address: 'Vadodara, Gujarat',
    companyUrl: '',
    logo: 'https://mywall-master.b-cdn.net/public/brandLogo/ogo.png-1755858179090?optimizer=image',
    banner: 'https://mywall-master.b-cdn.net/public/stores/Hotel%20,%20Restaurent%20&%20Salon%20Gifs.jpg-1755858520253?optimizer=image',
    bannerVideo: '',
    services: '',
    approval: 'Fast approval',
  },
  {
    id: 'salon-2',
    name: 'Higfeel Unisex Salon',
    category: 'Unisex Salon',
    instagramFollowers: '10k',
    location: 'Surat, Gujarat',
    address: 'Surat, Gujarat',
    companyUrl: '',
    logo: 'https://mywall-master.b-cdn.net/public/brandLogo/logo.jpg-1754309767139?optimizer=image',
    banner: 'https://mywall-master.b-cdn.net/public/listing/thumb.webp-1754309909069?optimizer=image',
    bannerVideo: '',
    services: 5000,
    approval: '',
  },
  {
    id: 'salon-3',
    name: 'The Sobo Nail Salon',
    category: 'Nail Salon',
    instagramFollowers: '10k',
    location: 'Navi Mumbai, Maharashtra',
    address: 'Navi Mumbai, Maharashtra',
    companyUrl: '',
    logo: 'https://mywall-master.b-cdn.net/public/brandLogo/Logo.jpg-1751025034477?optimizer=image',
    banner: 'https://mywall-master.b-cdn.net/public/listing/Hotel%20,%20Restaurent%20&%20Salon%20Gifs.png-1751025191428?optimizer=image',
    bannerVideo: '',
    services: 5000,
    approval: 'Fast approval',
  },
  {
    id: 'salon-4',
    name: 'The Hair Mahal Salon',
    category: 'Salon',
    instagramFollowers: '50k',
    location: 'New Delhi, Delhi',
    address: 'New Delhi, Delhi',
    companyUrl: '',
    logo: 'https://mywall-master.b-cdn.net/public/brandLogo/Logo.jpg-1749808193432?optimizer=image',
    banner: '',
    bannerVideo: 'https://mywall-master.b-cdn.net/public/listing/Hair Mahal Salon Gif.mp4-1750329947643?optimizer=image',
    services: '',
    approval: 'Fast approval',
  },
  {
    id: 'salon-5',
    name: 'Dreams Family Salon',
    category: 'Family Salon',
    instagramFollowers: '10k',
    location: 'Bengaluru, Karnataka',
    address: 'Bengaluru, Karnataka',
    companyUrl: '',
    logo: 'https://mywall-master.b-cdn.net/public/brandLogo/Logo.png-1758714444046?optimizer=image',
    banner: 'https://mywall-master.b-cdn.net/public/stores/1.webp-1758714472289?optimizer=image',
    bannerVideo: '',
    services: '',
    approval: '',
  },
  {
    id: 'salon-6',
    name: 'Iza Setia Makeovers',
    category: 'Makeup Studio',
    instagramFollowers: '25k',
    location: 'New Delhi, Delhi',
    address: 'New Delhi, Delhi',
    companyUrl: '',
    logo: 'https://mywall-master.b-cdn.net/public/brandLogo/Logo.png-1749803495017?optimizer=image',
    banner: 'https://mywall-master.b-cdn.net/public/listing/Thumb.webp-1749803717422?optimizer=image',
    bannerVideo: '',
    services: '',
    approval: 'Fast approval',
  },
  {
    id: 'salon-7',
    name: 'K-Glow | Korean Glow Studio',
    category: 'Skin & Glow Studio',
    instagramFollowers: '5k',
    location: 'Gurugram, Haryana',
    address: 'Gurugram, Haryana',
    companyUrl: '',
    logo: 'https://mywall-master.b-cdn.net/public/brandLogo/logo.png-1751975116059?optimizer=image',
    banner: '',
    bannerVideo: '',
    services: '',
    approval: '',
  },
  {
    id: 'salon-8',
    name: 'Athenian Salon & Academy',
    category: 'Salon & Academy',
    instagramFollowers: '10k',
    location: 'Bengaluru, Karnataka',
    address: 'Bengaluru, Karnataka',
    companyUrl: '',
    logo: 'https://mywall-master.b-cdn.net/public/brandLogo/logo.png-1758870421447?optimizer=image',
    banner: 'https://mywall-master.b-cdn.net/public/stores/2.webp-1758870481287?optimizer=image',
    bannerVideo: '',
    services: '',
    approval: '',
  },
  {
    id: 'salon-9',
    name: 'Evorra Unisex Salon',
    category: 'Unisex Salon',
    instagramFollowers: '10k',
    location: 'Bengaluru, Karnataka',
    address: 'Bengaluru, Karnataka',
    companyUrl: '',
    logo: 'https://mywall-master.b-cdn.net/public/brandLogo/logo.png-1758526220085?optimizer=image',
    banner: 'https://mywall-master.b-cdn.net/public/listing/3.webp-1758528349270?optimizer=image',
    bannerVideo: '',
    services: '',
    approval: '',
  },
  {
    id: 'salon-10',
    name: 'Scaarlett Unisex Salon',
    category: 'Unisex Salon',
    instagramFollowers: '5k',
    location: 'Hyderabad, Telangana',
    address: 'Hyderabad, Telangana',
    companyUrl: '',
    logo: 'https://mywall-master.b-cdn.net/public/brandLogo/loggo.png-1756991975210?optimizer=image',
    banner: 'https://mywall-master.b-cdn.net/public/stores/Thumbnail.webp-1756990593529?optimizer=image',
    bannerVideo: '',
    services: '',
    approval: 'Fast approval',
  },
];

export const mockSalonSliderData = [
  {
    id: 'slider-1',
    name: 'Shades Skin and Hair Care',
    instagramFollowers: '10k',
    location: 'Udaipur, Rajasthan',
    services: 4000,
    banner: '',
    bannerVideo: 'https://mywall-master.b-cdn.net/public/listing/Gif.mp4-1760076556806?optimizer=image',
    logo: 'https://mywall-master.b-cdn.net/public/brandLogo/Logo.jpg-1750673646152?optimizer=image',
  },
  {
    id: 'slider-2',
    name: 'Becks Beauty Bar Salon',
    instagramFollowers: '10k',
    location: 'Kolkata, Rajasthan',
    services: 8000,
    banner: '',
    bannerVideo: 'https://mywall-master.b-cdn.net/public/listing/Gif.mp4-1760079504067?optimizer=image',
    logo: 'https://mywall-master.b-cdn.net/public/brandLogo/logo.jpg-1749465640375?optimizer=image',
  },
  {
    id: 'slider-3',
    name: 'Sneha\'s Salon',
    instagramFollowers: '10k',
    location: 'Mumbai, Maharashtra',
    services: 7000,
    banner: '',
    bannerVideo: 'https://mywall-master.b-cdn.net/public/listing/Gid.mp4-1760077007346?optimizer=image',
    logo: 'https://mywall-master.b-cdn.net/public/brandLogo/logo.jpg-1747317477937?optimizer=image',
  },
  {
    id: 'slider-4',
    name: 'Hues Salon',
    instagramFollowers: '10k',
    location: 'Thane, Maharashtra',
    services: 3000,
    banner: '',
    bannerVideo: 'https://mywall-master.b-cdn.net/public/listing/Gif.mp4-1760078943774?optimizer=image',
    logo: 'https://mywall-master.b-cdn.net/public/brandLogo/hues%20log.jpg-1744272246502?optimizer=image',
  },
  {
    id: 'slider-5',
    name: 'Nailora',
    instagramFollowers: '5k',
    location: 'Mumbai, Maharashtra',
    services: '',
    banner: '',
    bannerVideo: 'https://mywall-master.b-cdn.net/public/listing/gif.mp4-1759926792211?optimizer=image',
    logo: 'https://mywall-master.b-cdn.net/public/brandLogo/WhatsApp%20Image%202025-10-09%20at%202.21.40%20PM.jpeg-1759999994569?optimizer=image',
  },
  {
    id: 'slider-6',
    name: 'Hair Master Salon Pitampura',
    instagramFollowers: '20k',
    location: 'New Delhi, Delhi',
    services: 10000,
    banner: '',
    bannerVideo: 'https://mywall-master.b-cdn.net/public/listing/Gid.mp4-1760077775290?optimizer=image',
    logo: 'https://mywall-master.b-cdn.net/public/brandLogo/Logo.jpg-1748256634282?optimizer=image',
  },
  {
    id: 'slider-7',
    name: 'Toni & Guy Hairdressing, Kasavanahalli',
    instagramFollowers: '5k',
    location: 'Bengaluru, Karnataka',
    services: '',
    banner: 'https://mywall-master.b-cdn.net/public/stores/Thumbnail.webp-1763548966390?optimizer=image',
    bannerVideo: '',
    logo: 'https://mywall-master.b-cdn.net/public/brandLogo/Logo.jpg-1763548934139?optimizer=image',
  },
  {
    id: 'slider-8',
    name: 'Hair Master and Luxury Salon, Shalimar Bagh',
    instagramFollowers: '20k',
    location: 'New Delhi, Delhi',
    services: 10000,
    banner: '',
    bannerVideo: 'https://mywall-master.b-cdn.net/public/listing/Gif.mp4-1760080250839?optimizer=image',
    logo: 'https://mywall-master.b-cdn.net/public/brandLogo/Logo.jpg-1748256634282?optimizer=image',
  },
  {
    id: 'slider-9',
    name: 'Tony & Guy Essensual Hara',
    instagramFollowers: '5k',
    location: 'Bengaluru, Karnataka',
    services: '',
    banner: 'https://mywall-master.b-cdn.net/public/stores/Thumbanil.webp-1763549036833?optimizer=image',
    bannerVideo: '',
    logo: 'https://mywall-master.b-cdn.net/public/brandLogo/Logo.jpg-1763548934139?optimizer=image',
  },
  {
    id: 'slider-10',
    name: 'Geetanjali Studio - Hair and Beauty Salon',
    instagramFollowers: '30k',
    location: 'Gurugram, Haryana',
    services: 8000,
    banner: '',
    bannerVideo: 'https://mywall-master.b-cdn.net/public/listing/geetjali.mp4-1745827421795?optimizer=image',
    logo: 'https://mywall-master.b-cdn.net/public/brandLogo/geetanjali.png-1744439409205?optimizer=image',
  },
  {
    id: 'slider-11',
    name: 'New Hair Signature',
    instagramFollowers: '10k',
    location: 'New Delhi, Delhi',
    services: '',
    banner: '',
    bannerVideo: 'https://mywall-master.b-cdn.net/public/listing/Gif.mp4-1760351155610?optimizer=image',
    logo: 'https://mywall-master.b-cdn.net/public/brandLogo/logo.png-1758712365348?optimizer=image',
  },
];
